server:
  port: 8082
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: Ninh
    password: 1234

#  jpa:
#    hibernate:
#      ddl-auto: update
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka